### ISSUE TITLE
How you added disqus comments on your blog ?

### ISSUE THREAD

**Issue by collegeimprovements** [twin/twin.github.io#15]
I was searchig for disqus code or `comments:true` but couldn't find it. I'm just curious where you put the disqus code!

**Comment by silvenon** [comment]
The code is in the [`comments.html`](https://github.com/twin/twin.github.io/blob/ed0705380d58aee025c1af68963042cb77ed095c/_includes/comments.html). GitHub's project-wide search bar can help with these problems in the future :wink:

**Comment by collegeimprovements** [comment]
Oh ya! Thanks :)
