### ISSUE TITLE
Style <code> tags which are links

### ISSUE THREAD

**Issue by janko-m** [twin/twin.github.io#16]
In GitHub I can make a [`<code>`](#) tag which is also a link, and GitHub colors the text inside the tag so that you know it's a link. It would be cool if our blog also had this (currently a \<code\> link only receives a red border, which is not enough).

**Comment by janko-m** [comment]
Thanks! :ok_hand:

**Comment by janko-m** [comment]
Misliš da bi možda mogao napraviti da nema crveni border? Ovako mi se ipak malo ističe previše.

**Comment by silvenon** [comment]
Jesam.

**Comment by janko-m** [comment]
Savršeno, tnx!
