### ISSUE TITLE
Subscribe via email

### ISSUE THREAD

**Issue by janko-m** [twin/twin.github.io#26]
> I like your writes, consider creating a mail subscription, I'd like your writes to land my inbox. 

Maybe it's worthwhile to add ability for email subscription. I don't know how difficult it would be to add, also considering that it should be scoped to a single author.

**Comment by silvenon** [comment]
Shouldn't there be a feed client which can redirect our Atom feed to email? We already have a feed, so I think it's an overkill to have a newsletter as well.

**Comment by janko-m** [comment]
Yeah, probably.
